language: node_js
sudo: false
node_js:
  - "6"
before_script:
  - npm install --force --no-save
script:
  - npm run lint
  - npm run flow
  - npm run build
  - npm run docs:install
  - npm run docs:build
  - npm run test
  - npm run test:unit
  - npm run test:e2e
