# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    branches:
      only:
        - master
    docker:
      # specify the version you desire here
      - image: circleci/node:9
    environment:
      - TERM: xterm
      - CHROME_BIN: /usr/bin/google-chrome

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: Install apt dependencies
          command: |
            curl https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
            sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            sudo apt-get update -qq
            sudo apt-get install -qy libelf1 google-chrome-stable

      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}

      - run:
          name: Install dependencies
          command: |
            npm install

      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules

      - run:
          name: Run eslint check
          command: |
            npm run lint

      - run:
          name: Run flow check
          command: |
            npm run flow

      - run:
          name: Build package
          command: |
            npm run build

      - run:
          name: Build docs
          command: |
            npm run docs:install
            npm run docs:build

      - run:
          name: Run tests
          command: |
            npm run test
